definitions = {
    'ID': '8480800',
    'Name': 'Quinn Hughes',
    'Position': 'D',
    'Team': 'VAN',
    "timeOnIce" : "27:28",
    "assists" : 3,
    "goals" : 0,
    "pim" : 0,
    "shots" : 3,
    "games" : 1,
    "hits" : 0,
    "powerPlayGoals" : 0,
    "powerPlayPoints" : 1,
    "powerPlayTimeOnIce" : "01:12",
    "evenTimeOnIce" : "26:16",
    "penaltyMinutes" : "0",
    "faceOffPct" : 50.0,
    "shotPct" : 0.0,
    "gameWinningGoals" : 0,
    "overTimeGoals" : 0,
    "shortHandedGoals" : 0,
    "shortHandedPoints" : 0,
    "shortHandedTimeOnIce" : "00:00",
    "blocked" : 0,
    "plusMinus" : 0,
    "points" : 3,
    "shifts" : 32,
    "fanPts" : 0,
    'timeOnIce_W': '',
    'assists_W': '',
    'goals_W': '',
    'pim_W': '',
    'shots_W': '',
    'games_W': '',
    'hits_W': '',
    'powerPlayGoals_W': '',
    'powerPlayPoints_W': '',
    'powerPlayTimeOnIce_W': '',
    'evenTimeOnIce_W': '',
    'penaltyMinutes_W': '',
    'faceOffPct_W': '',
    'shotPct_W': '',
    'gameWinningGoals_W': '',
    'overTimeGoals_W': '',
    'shortHandedGoals_W': '',
    'shortHandedPoints_W': '',
    'shortHandedTimeOnIce_W': '',
    'blocked_W': '',
    'plusMinus_W': '',
    'points_W': '',
    'shifts_W': '',
    'fanPts_W': '',
    'truth': 0,
}

def getKeys():
    return list(definitions.keys())
